name: Deploy
on:
  push:
    branches:
      - hosted-api
      - open-data
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run build -- --pathPrefix="/stac-browser/${{ github.ref_name }}" --historyMode=hash
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          destination_dir: ${{ github.ref_name }}
          user_name: 'STAC Browser CI'
          user_email: matthias.mohr@radiant.earth